spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_system
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgresSLDialect
  mail:
    host: localhost
    port: 1025
    username: user
    password: pass
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000