services:
  postgres-sql:
    container_name: postgres-sql-crs
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: car_rental_system
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-crs
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge